#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
PATH="${PATH}:${SCRIPT_PATH}"

# Header
ARGUMENTS="\
"
. "${SCRIPT_PATH}/share/header"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1;;
  esac; shift
done

#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" > /dev/null
{
  mkdir -p ${HOME}/.config/curate-pkg
  for package_manager in apt brew dnf eopkg flatpak go nix npm pacman snap; do
    if command -v ${package_manager} &> /dev/null; then
      if [[ ! -f ${HOME}/.config/curate-pkg/${package_manager}.yaml ]]; then
        install ${script_path}/share/empty.yaml ${HOME}/.config/curate-pkg/${package_manager}.yaml
      fi
    fi
  done

  # Needs to run as root but keep ${HOME}
  (( EUID != 0 )) && exec sudo -H ./install_with_sudo
}
popd 1> /dev/null
