#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
ARGUMENTS="\
  [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/share/portunus/lib/header"

# Parse arguments.
pkgdir=
while (( ${#} > 0 )); do
  case "${1}" in
  # [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
  '-p'|'--prefix') shift && pkgdir="${1}";;
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1;;
  esac; shift
done

#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" > /dev/null
{
  ./share/install-initial-configuration

  if (( EUID == 0 )); then
    ./share/install-with-sudo -p "${pkgdir}"
  else
    sudo ./share/install-initial-configuration
    # Needs to run as root but keep ${HOME}
    sudo ./share/install-with-sudo -p "${pkgdir}"
  fi
}
popd 1> /dev/null
