#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
PATH="${PATH}:${SCRIPT_PATH}"

# Header
ARGUMENTS="\
"
. "${SCRIPT_PATH}/header"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1;;
  esac; shift
done

#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" 1> /dev/null
{
  mkdir -p /usr/local/bin
  install ../bin/* /usr/local/bin
  mkdir -p /usr/local/share/curate-pkg/samples
  mkdir -p /usr/local/share/curate-pkg/package-managers
  install ./header /usr/local/share/curate-pkg
  install ./spinner /usr/local/share/curate-pkg
  install ./*.yaml /usr/local/share/curate-pkg
  install ./package-managers/*.sh /usr/local/share/curate-pkg/package-managers
  install ./samples/* /usr/local/share/curate-pkg/samples
  if ! command -v yq &> /dev/null; then
    pip install share/yq-2.3.4-py2.py3-none-any.whl
  fi
}
popd 1> /dev/null
