#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
PATH="${PATH}:${SCRIPT_PATH}"

# Header
ARGUMENTS="\
  [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
"
. "${SCRIPT_PATH}/curate-pkg/lib/header"

# Parse arguments.
pkgdir=
while (( ${#} > 0 )); do
  case "${1}" in
  # [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
  '-p'|'--prefix') shift && pkgdir="${1}";;
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1;;
  esac; shift
done


#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" 1> /dev/null
{
  # Install.
  mkdir -p "${pkgdir}/usr/local/bin"
  install ../bin/curate-pkg "${pkgdir}/usr/local/bin"
  install ../bin/curate-pkg-one "${pkgdir}/usr/local/bin"
  mkdir -p "${pkgdir}/usr/local/share/curate-pkg/samples"
  mkdir -p "${pkgdir}/usr/local/share/curate-pkg/lib"
  mkdir -p "${pkgdir}/usr/local/share/curate-pkg/package-managers"
  install ./curate-pkg/lib/* "${pkgdir}/usr/local/share/curate-pkg/lib"
  install ./*.yaml "${pkgdir}/usr/local/share/curate-pkg"
  install ./package-managers/*.sh "${pkgdir}/usr/local/share/curate-pkg/package-managers"
  install ./samples/* "${pkgdir}/usr/local/share/curate-pkg/samples"

  # Install bash_completions.
  set +e
  bash_completions="$(pkg-config --variable=completionsdir bash-completion)"
  result="${?}"
  set -e
  if (( result != 0 )); then
    bash_completions='/usr/share/bash-completion/completions'
  fi
  bash_completions="${pkgdir}/${bash_completions}/curate-pkg"
  mkdir -p "${bash_completions}"
  install ./bash-completion "${bash_completions}"

  # Install unp if not already installed.
  if ! command -v unp &> /dev/null; then
    install ./share/dependencies/unp "${pkgdir}/usr/local/bin"
  fi

  # Install yq if not already installed.
  if ! command -v yq &> /dev/null; then
    pip install ./share/dependencies/yq-2.7.0-py2.py3-none-any.whl
  fi
}
popd 1> /dev/null
